name: my_intro
description: "Introduction package"
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.1
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
